export const agentCategories = [
  "Atendimento",
  "Comercial",
  "Operações",
  "Conhecimento",
] as const;

export const marketplaceAgents = [
  {
    id: "atendimento",
    number: "01",
    title: "Atendimento IA",
    category: "Experiência do cliente",
    description: "Triagem e atendimento multicanal com contexto e encaminhamento humano.",
    integrations: ["WhatsApp", "Telegram", "APIs"],
    accent: "#EC4899",
    surface: "#25101D",
  },
  {
    id: "sdr",
    number: "02",
    title: "SDR IA",
    category: "Operação comercial",
    description: "Qualificação, follow-up e organização de oportunidades para o time comercial.",
    integrations: ["CRM", "E-mail", "APIs"],
    accent: "#F97316",
    surface: "#2A1408",
  },
  {
    id: "juridico",
    number: "03",
    title: "Jurídico IA",
    category: "Apoio documental",
    description: "Organização, triagem e apoio a rotinas documentais com revisão humana.",
    integrations: ["Documentos", "Cloud", "APIs"],
    accent: "#C4B5FD",
    surface: "#1C1730",
  },
  {
    id: "clinicas",
    number: "04",
    title: "Clínicas IA",
    category: "Relacionamento",
    description: "Agendamento, orientação inicial e comunicação organizada com pacientes.",
    integrations: ["WhatsApp", "Agenda", "APIs"],
    accent: "#14B8A6",
    surface: "#071B1A",
  },
  {
    id: "financeiro",
    number: "05",
    title: "Financeiro IA",
    category: "Apoio operacional",
    description: "Cobranças, alertas e acompanhamento de rotinas financeiras recorrentes.",
    integrations: ["ERP", "E-mail", "APIs"],
    accent: "#F4B860",
    surface: "#281E0B",
  },
  {
    id: "desenvolvedor",
    number: "06",
    title: "Desenvolvedor IA",
    category: "Engenharia assistida",
    description: "Apoio a código, documentação, testes e qualidade no ciclo de desenvolvimento.",
    integrations: ["Git", "Cloud", "APIs"],
    accent: "#93C5FD",
    surface: "#0B1930",
  },
  {
    id: "whatsapp",
    number: "07",
    title: "WhatsApp IA",
    category: "Conversas conectadas",
    description: "Conversas automatizadas com contexto, regras e transferência para a equipe.",
    integrations: ["WhatsApp", "CRM", "APIs"],
    accent: "#A3E635",
    surface: "#142006",
  },
  {
    id: "automacao",
    number: "08",
    title: "Automação IA",
    category: "Execução de fluxos",
    description: "Execução e monitoramento de fluxos entre dados, canais e sistemas.",
    integrations: ["Node.js", "Python", "APIs"],
    accent: "#8B5CF6",
    surface: "#171027",
  },
] as const;

export const platformModules = [
  {
    id: "agents",
    index: "01",
    title: "Agentes",
    summary: "Catálogo, status e contexto dos agentes previstos para a operação.",
    accent: "#EC4899",
    rows: ["Atendimento IA", "SDR IA", "Automação IA"],
  },
  {
    id: "services",
    index: "02",
    title: "Servicos",
    summary: "Escopo, responsáveis e acompanhamento dos serviços contratados.",
    accent: "#8B5CF6",
    rows: ["Software sob medida", "Cloud gerenciada", "Integrações"],
  },
  {
    id: "projects",
    index: "03",
    title: "Projetos",
    summary: "Etapas, entregas e progresso reunidos em uma única visão.",
    accent: "#93C5FD",
    rows: ["Descoberta", "Construção", "Validação"],
  },
  {
    id: "tickets",
    index: "04",
    title: "Tickets",
    summary: "Solicitações, prioridade, histórico e retorno da equipe.",
    accent: "#F97316",
    rows: ["Nova solicitação", "Em acompanhamento", "Resolvidos"],
  },
  {
    id: "billing",
    index: "05",
    title: "Financeiro",
    summary: "Faturas, vencimentos e documentos quando o módulo estiver ativo.",
    accent: "#F4B860",
    rows: ["Proxima fatura", "Documentos", "Historico"],
  },
  {
    id: "automations",
    index: "06",
    title: "Automações",
    summary: "Fluxos, execuções e alertas operacionais em um mesmo contexto.",
    accent: "#14B8A6",
    rows: ["Fluxos ativos", "Execuções", "Alertas"],
  },
  {
    id: "notifications",
    index: "07",
    title: "Notificações",
    summary: "Atualizações importantes da conta e dos projetos sem ruído.",
    accent: "#C4B5FD",
    rows: ["Conta", "Projetos", "Operacao"],
  },
] as const;

export const differentials = [
  {
    label: "AI-FIRST",
    description: "Inteligência incorporada desde a arquitetura.",
    background: "#F6F4EF",
    foreground: "#050507",
    accent: "#6D28D9",
  },
  {
    label: "24 / 7",
    description: "Agentes preparados para operação contínua, conforme o escopo contratado.",
    background: "#17181E",
    foreground: "#F6F4EF",
    accent: "#A3E635",
  },
  {
    label: "CONNECTED",
    description: "Sistemas, dados e automações no mesmo ecossistema.",
    background: "#0B1930",
    foreground: "#F6F4EF",
    accent: "#93C5FD",
  },
  {
    label: "CUSTOM",
    description: "Tecnologia construída para a realidade de cada operação.",
    background: "#F4E9F1",
    foreground: "#050507",
    accent: "#DB2777",
  },
  {
    label: "CLOUD",
    description: "Infraestrutura preparada para crescer com previsibilidade.",
    background: "#071B1A",
    foreground: "#F6F4EF",
    accent: "#14B8A6",
  },
] as const;
