export const revealFragmentedItems = [
  "Processos manuais",
  "Tarefas repetitivas",
  "Sistemas desconectados",
  "Atendimento lento",
  "Dados espalhados",
  "Retrabalho",
] as const;

export const revealConnectedItems = [
  "Agentes de IA",
  "Automações",
  "Sistemas conectados",
  "Operação em tempo real",
  "Dados centralizados",
  "Escalabilidade",
] as const;

export const technologies = [
  "OpenAI",
  "Next.js",
  "TypeScript",
  "Node.js",
  "Python",
  "PostgreSQL",
  "Supabase",
  "Docker",
  "Vercel",
  "Hostinger",
  "WhatsApp",
  "Telegram",
  "APIs",
  "AUTOMAÇÕES",
] as const;

export const capabilities = [
  {
    value: "24/7",
    counter: 24,
    suffix: "/7",
    label: "AGENTES DISPONÍVEIS",
    tone: "dark",
  },
  {
    value: "1",
    counter: 1,
    suffix: "",
    label: "ECOSSISTEMA CONECTADO",
    tone: "light",
  },
  {
    value: "API",
    label: "INTEGRAÇÕES ABERTAS",
    tone: "blue",
  },
  {
    value: "CLOUD",
    label: "INFRAESTRUTURA ESCALÁVEL",
    tone: "warm",
  },
] as const;

export const services = [
  {
    id: "software",
    number: "01",
    title: "DESENVOLVIMENTO DE SOFTWARE",
    shortTitle: "Software",
    description: "Sistemas web, plataformas internas e produtos digitais sob medida.",
    practical: "Ideal para organizar fluxos críticos, portais internos e produtos próprios.",
    technologies: ["Next.js", "TypeScript", "Node.js"],
    color: "#6D28D9",
    surface: "#F6F4EF",
    ink: "#050507",
  },
  {
    id: "agents",
    number: "02",
    title: "AGENTES DE INTELIGÊNCIA ARTIFICIAL",
    shortTitle: "Agentes IA",
    description: "Agentes especializados para atendimento, vendas, jurídico, clínicas e operações.",
    practical: "Apoio contínuo para triagem, respostas, análise e execução assistida.",
    technologies: ["OpenAI", "APIs", "WhatsApp"],
    color: "#EC4899",
    surface: "#17181E",
    ink: "#F6F4EF",
  },
  {
    id: "automation",
    number: "03",
    title: "AUTOMAÇÃO DE PROCESSOS",
    shortTitle: "Automação",
    description: "Fluxos que conectam dados, mensagens, tarefas e sistemas.",
    practical: "Reduz retrabalho e conecta etapas que hoje dependem de operação manual.",
    technologies: ["Node.js", "Python", "APIs"],
    color: "#F97316",
    surface: "#2A1408",
    ink: "#F6F4EF",
  },
  {
    id: "saas",
    number: "04",
    title: "PLATAFORMAS SAAS",
    shortTitle: "SaaS",
    description: "Produtos recorrentes com arquitetura preparada para operação e crescimento.",
    practical: "Base para produto digital, assinatura, onboarding e áreas autenticadas.",
    technologies: ["Next.js", "PostgreSQL", "Supabase"],
    color: "#2563EB",
    surface: "#E7F0FF",
    ink: "#050507",
  },
  {
    id: "cloud",
    number: "05",
    title: "CLOUD E INFRAESTRUTURA",
    shortTitle: "Cloud",
    description: "Ambientes de deploy, observabilidade, segurança e escalabilidade.",
    practical: "Prepara a operação para crescer com deploy previsível e monitoramento.",
    technologies: ["Docker", "Vercel", "Hostinger"],
    color: "#14B8A6",
    surface: "#071B1A",
    ink: "#F6F4EF",
  },
  {
    id: "integrations",
    number: "06",
    title: "APIS E INTEGRAÇÕES",
    shortTitle: "Integrações",
    description: "Conexão entre sistemas, canais, pagamentos e ferramentas de negócio.",
    practical: "Integra canais e dados para que a operação não dependa de ilhas soltas.",
    technologies: ["APIs", "Telegram", "Supabase"],
    color: "#C4B5FD",
    surface: "#F4F0FF",
    ink: "#050507",
  },
] as const;
